import chrome from "./assets/chrome.webp";
import web from "./assets/web.webp";
export const projects = [
  {
    id: 1,
    title: "Keyboard",
    tag: "Web App",
    tagIcon: web,
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla elementum ac libero sit amet efficitur. Nulla tristique, ex eget facilisis auctor, nisl dui.",
    tech: "React, Redux, Tailwind CSS",
    githubLink: "https://github.com/shrutishri2208/keyboard",
    viewLink: "https://keyboard-chi.vercel.app/",
    viewText: "View",
  },
  {
    id: 2,
    title: "Textplay",
    tag: "Extension",
    tagIcon: chrome,
    desc: "TextPlay is a chrome extension that suggests YouTube videos related to the webpage you are currently browsing. ",
    tech: "HTML, CSS, JavaScript, YouTube Data API v3",
    githubLink: "https://github.com/shrutishri2208/page-play",
    viewLink: "http://page-play.shrutz.xyz/",
    viewText: "Download",
  },
  // {
  //   id: 3,
  //   title: "Murk",
  //   tag: "Mobile Game",
  //   desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla elementum ac libero sit amet efficitur. Nulla tristique, ex eget facilisis auctor, nisl dui.",
  //   tech: "Tag1, Tag2, Tag3",
  //   githubLink: "",
  //   viewLink: "",
  //   viewText: "Download",
  // },
  // {
  //   id: 4,
  //   title: "Word Wise",
  //   tag: "Chrome Extension",
  //   desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla elementum ac libero sit amet efficitur. Nulla tristique, ex eget facilisis auctor, nisl dui.",
  //   tech: "Tag1, Tag2, Tag3",
  //   githubLink: "",
  //   viewLink: "",
  //   viewText: "Download",
  // },
];

export const clones = [
  {
    id: 1,
    title: "Netflux",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla elementum ac libero sit amet efficitur. Nulla tristique, ex eget facilisis auctor, nisl dui.",
    tech: "React, Redux, Tailwind CSS, Rapid API, material UI, react-router",
    githubLink: "https://github.com/shrutishri2208/netflix-clone",
  },
  {
    id: 2,
    title: "Zwiggy",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla elementum ac libero sit amet efficitur. Nulla tristique, ex eget facilisis auctor, nisl dui.",
    tech: "React Native, Redux, NativeWind, Sanity CMS",
    githubLink: "https://github.com/shrutishri2208/food-delivery-app",
  },
];

export const sides = [
  {
    id: 1,
    title: "Murk",
    tag: "Game",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla elementum ac libero sit amet efficitur. ",
    tech: "Tag1, Tag2, Tag3",
    githubLink: "",
    viewLink: "",
    viewText: "Download",
  },
  {
    id: 2,
    title: "Pageplay",
    tag: "Chrome Extension",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla elementum ac libero sit amet efficitur. ",
    tech: "Tag1, Tag2, Tag3",
    githubLink: "",
    viewLink: "",
    viewText: "Download",
  },
  {
    id: 3,
    title: "Keyboard",
    tag: "Web App",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla elementum ac libero sit amet efficitur. ",
    tech: "Tag1, Tag2, Tag3",
    githubLink: "",
    viewLink: "",
    viewText: "View",
  },
  {
    id: 4,
    title: "Word Wise",
    tag: "Chrome Extension",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla elementum ac libero sit amet efficitur. ",
    tech: "Tag1, Tag2, Tag3",
    githubLink: "",
    viewLink: "",
    viewText: "Download",
  },
];
